### ISSUE TITLE
Bot does not remove info not returned by Galaxy Info API

### ISSUE THREAD

**Issue by CornHusker89** [Galaxypedia-Wiki/ketchupbot-updater#37]
I get that this behavior is intentional, but this can also cause problems.

An example of this is when permits got removed for limited ships, so the Galaxy Info API stopped returning permit information (bc those ships didn't require permits anymore), however because of this behavior, limited ship infoboxes reported that these ships still required permits, which was false.

I think that we should implement a system where if the api dosen't return anything for an infobox parameter, the bot then checks if the api ever did return a result. If it never did return something, the bot will leave it as it is (for example, the ship creator section of the infobox). If the api did return something in the past, it will remove it from the infobox (ex. limited ship permits). 

This is the affected code segment
https://github.com/smallketchup82/ketchupbot-updater/blob/f0af630db0788a47e052bf4a69f718722e2c9648/src/index.ts#L367-L374

**Comment by smallketchup82** [comment]
@CornHusker89 okay i saw this issue again and i'll give you my response (sorry for how long it took)

essentially, this is unfeasible from a technical standpoint. how do you efficiently differentiate between what ketchupbot put on the page, and what other people put down? say a user adds a misc parameter, like manufacturing fee. but since ketchupbot doesnt get that information from the api, it'll delete it. this can EASILY become invasive and annoying. you do provide a solution:

> I think that we should implement a system where if the api dosen't return anything for an infobox parameter, the bot then checks if the api ever did return a result. If it never did return something, the bot will leave it as it is (for example, the ship creator section of the infobox). If the api did return something in the past, it will remove it from the infobox (ex. limited ship permits).

but my question now is, how do you plan on persisting this for EVERY installation of ketchupbot? and would this really justify making ketchupbot stateful, and the overhead that comes with that?

if we really care about deleting stale parameters—where devs suddenly drop a parameter and now we want to remove it from every infobox—we can either delete that parameter from the infobox template to make it not display, or use something like https://www.mediawiki.org/wiki/Extension:Replace_Text/en#Usage to delete the parameter off of every ship page.

though, in my c# version of ketchupbot, i already provided a method of excluding certain parameters from the end result (albeit in a GlobalConfig object which i should probably make user accessible), which essentially "deletes" the parameter. i think this is a good compromise for this issue

**Comment by smallketchup82** [comment]
@CornHusker89 do you have anything else to add on here or should i close this issue as wontfix?

**Comment by CornHusker89** [comment]
all g from me
